export const championNameById = {
    '1': [ 'Annie', 'Annie', '애니' ],
    '2': [ 'Olaf', 'Olaf', '올라프' ],
    '3': [ 'Galio', 'Galio', '갈리오' ],
    '4': [ 'TwistedFate', 'Twisted Fate', '트위스티드 페이트' ],
    '5': [ 'XinZhao', 'Xin Zhao', '신 짜오' ],
    '6': [ 'Urgot', 'Urgot', '우르곳' ],
    '7': [ 'Leblanc', 'LeBlanc', '르블랑' ],
    '8': [ 'Vladimir', 'Vladimir', '블라디미르' ],
    '9': [ 'FiddleSticks', 'Fiddlesticks', '피들스틱' ],
    '10': [ 'Kayle', 'Kayle', '케일' ],
    '11': [ 'MasterYi', 'Master Yi', '마스터 이' ],
    '12': [ 'Alistar', 'Alistar', '알리스타' ],
    '13': [ 'Ryze', 'Ryze', '라이즈' ],
    '14': [ 'Sion', 'Sion', '사이온' ],
    '15': [ 'Sivir', 'Sivir', '시비르' ],
    '16': [ 'Soraka', 'Soraka', '소라카' ],
    '17': [ 'Teemo', 'Teemo', '티모' ],
    '18': [ 'Tristana', 'Tristana', '트리스타나' ],
    '19': [ 'Warwick', 'Warwick', '워윅' ],
    '20': [ 'Nunu', 'Nunu & Willump', '누누와 윌럼프' ],
    '21': [ 'MissFortune', 'Miss Fortune', '미스 포츈' ],
    '22': [ 'Ashe', 'Ashe', '애쉬' ],
    '23': [ 'Tryndamere', 'Tryndamere', '트린다미어' ],
    '24': [ 'Jax', 'Jax', '잭스' ],
    '25': [ 'Morgana', 'Morgana', '모르가나' ],
    '26': [ 'Zilean', 'Zilean', '질리언' ],
    '27': [ 'Singed', 'Singed', '신지드' ],
    '28': [ 'Evelynn', 'Evelynn', '이블린' ],
    '29': [ 'Twitch', 'Twitch', '트위치' ],
    '30': [ 'Karthus', 'Karthus', '카서스' ],
    '31': [ 'Chogath', "Cho'Gath", '초가스' ],
    '32': [ 'Amumu', 'Amumu', '아무무' ],
    '33': [ 'Rammus', 'Rammus', '람머스' ],
    '34': [ 'Anivia', 'Anivia', '애니비아' ],
    '35': [ 'Shaco', 'Shaco', '샤코' ],
    '36': [ 'DrMundo', 'Dr. Mundo', '문도 박사' ],
    '37': [ 'Sona', 'Sona', '소나' ],
    '38': [ 'Kassadin', 'Kassadin', '카사딘' ],
    '39': [ 'Irelia', 'Irelia', '이렐리아' ],
    '40': [ 'Janna', 'Janna', '잔나' ],
    '41': [ 'Gangplank', 'Gangplank', '갱플랭크' ],
    '42': [ 'Corki', 'Corki', '코르키' ],
    '43': [ 'Karma', 'Karma', '카르마' ],
    '44': [ 'Taric', 'Taric', '타릭' ],
    '45': [ 'Veigar', 'Veigar', '베이가' ],
    '48': [ 'Trundle', 'Trundle', '트런들' ],
    '50': [ 'Swain', 'Swain', '스웨인' ],
    '51': [ 'Caitlyn', 'Caitlyn', '케이틀린' ],
    '53': [ 'Blitzcrank', 'Blitzcrank', '블리츠크랭크' ],
    '54': [ 'Malphite', 'Malphite', '말파이트' ],
    '55': [ 'Katarina', 'Katarina', '카타리나' ],
    '56': [ 'Nocturne', 'Nocturne', '녹턴' ],
    '57': [ 'Maokai', 'Maokai', '마오카이' ],
    '58': [ 'Renekton', 'Renekton', '레넥톤' ],
    '59': [ 'JarvanIV', 'Jarvan IV', '자르반 4세' ],
    '60': [ 'Elise', 'Elise', '엘리스' ],
    '61': [ 'Orianna', 'Orianna', '오리아나' ],
    '62': [ 'MonkeyKing', 'Wukong', '오공' ],
    '63': [ 'Brand', 'Brand', '브랜드' ],
    '64': [ 'LeeSin', 'Lee Sin', '리 신' ],
    '67': [ 'Vayne', 'Vayne', '베인' ],
    '68': [ 'Rumble', 'Rumble', '럼블' ],
    '69': [ 'Cassiopeia', 'Cassiopeia', '카시오페아' ],
    '72': [ 'Skarner', 'Skarner', '스카너' ],
    '74': [ 'Heimerdinger', 'Heimerdinger', '하이머딩거' ],
    '75': [ 'Nasus', 'Nasus', '나서스' ],
    '76': [ 'Nidalee', 'Nidalee', '니달리' ],
    '77': [ 'Udyr', 'Udyr', '우디르' ],
    '78': [ 'Poppy', 'Poppy', '뽀삐' ],
    '79': [ 'Gragas', 'Gragas', '그라가스' ],
    '80': [ 'Pantheon', 'Pantheon', '판테온' ],
    '81': [ 'Ezreal', 'Ezreal', '이즈리얼' ],
    '82': [ 'Mordekaiser', 'Mordekaiser', '모데카이저' ],
    '83': [ 'Yorick', 'Yorick', '요릭' ],
    '84': [ 'Akali', 'Akali', '아칼리' ],
    '85': [ 'Kennen', 'Kennen', '케넨' ],
    '86': [ 'Garen', 'Garen', '가렌' ],
    '89': [ 'Leona', 'Leona', '레오나' ],
    '90': [ 'Malzahar', 'Malzahar', '말자하' ],
    '91': [ 'Talon', 'Talon', '탈론' ],
    '92': [ 'Riven', 'Riven', '리븐' ],
    '96': [ 'KogMaw', "Kog'Maw", '코그모' ],
    '98': [ 'Shen', 'Shen', '쉔' ],
    '99': [ 'Lux', 'Lux', '럭스' ],
    '101': [ 'Xerath', 'Xerath', '제라스' ],
    '102': [ 'Shyvana', 'Shyvana', '쉬바나' ],
    '103': [ 'Ahri', 'Ahri', '아리' ],
    '104': [ 'Graves', 'Graves', '그레이브즈' ],
    '105': [ 'Fizz', 'Fizz', '피즈' ],
    '106': [ 'Volibear', 'Volibear', '볼리베어' ],
    '107': [ 'Rengar', 'Rengar', '렝가' ],
    '110': [ 'Varus', 'Varus', '바루스' ],
    '111': [ 'Nautilus', 'Nautilus', '노틸러스' ],
    '112': [ 'Viktor', 'Viktor', '빅토르' ],
    '113': [ 'Sejuani', 'Sejuani', '세주아니' ],
    '114': [ 'Fiora', 'Fiora', '피오라' ],
    '115': [ 'Ziggs', 'Ziggs', '직스' ],
    '117': [ 'Lulu', 'Lulu', '룰루' ],
    '119': [ 'Draven', 'Draven', '드레이븐' ],
    '120': [ 'Hecarim', 'Hecarim', '헤카림' ],
    '121': [ 'Khazix', "Kha'Zix", '카직스' ],
    '122': [ 'Darius', 'Darius', '다리우스' ],
    '126': [ 'Jayce', 'Jayce', '제이스' ],
    '127': [ 'Lissandra', 'Lissandra', '리산드라' ],
    '131': [ 'Diana', 'Diana', '다이애나' ],
    '133': [ 'Quinn', 'Quinn', '퀸' ],
    '134': [ 'Syndra', 'Syndra', '신드라' ],
    '136': [ 'AurelionSol', 'Aurelion Sol', '아우렐리온 솔' ],
    '141': [ 'Kayn', 'Kayn', '케인' ],
    '142': [ 'Zoe', 'Zoe', '조이' ],
    '143': [ 'Zyra', 'Zyra', '자이라' ],
    '145': [ 'Kaisa', "Kai'Sa", '카이사' ],
    '147': [ 'Seraphine', 'Seraphine', '세라핀' ],
    '150': [ 'Gnar', 'Gnar', '나르' ],
    '154': [ 'Zac', 'Zac', '자크' ],
    '157': [ 'Yasuo', 'Yasuo', '야스오' ],
    '161': [ 'Velkoz', "Vel'Koz", '벨코즈' ],
    '163': [ 'Taliyah', 'Taliyah', '탈리야' ],
    '164': [ 'Camille', 'Camille', '카밀' ],
    '166': [ 'Akshan', 'Akshan', '아크샨' ],
    '201': [ 'Braum', 'Braum', '브라움' ],
    '202': [ 'Jhin', 'Jhin', '진' ],
    '203': [ 'Kindred', 'Kindred', '킨드레드' ],
    '222': [ 'Jinx', 'Jinx', '징크스' ],
    '223': [ 'TahmKench', 'Tahm Kench', '탐 켄치' ],
    '234': [ 'Viego', 'Viego', '비에고' ],
    '235': [ 'Senna', 'Senna', '세나' ],
    '236': [ 'Lucian', 'Lucian', '루시안' ],
    '238': [ 'Zed', 'Zed', '제드' ],
    '240': [ 'Kled', 'Kled', '클레드' ],
    '245': [ 'Ekko', 'Ekko', '에코' ],
    '246': [ 'Qiyana', 'Qiyana', '키아나' ],
    '254': [ 'Vi', 'Vi', '바이' ],
    '266': [ 'Aatrox', 'Aatrox', '아트록스' ],
    '267': [ 'Nami', 'Nami', '나미' ],
    '268': [ 'Azir', 'Azir', '아지르' ],
    '350': [ 'Yuumi', 'Yuumi', '유미' ],
    '360': [ 'Samira', 'Samira', '사미라' ],
    '412': [ 'Thresh', 'Thresh', '쓰레쉬' ],
    '420': [ 'Illaoi', 'Illaoi', '일라오이' ],
    '421': [ 'RekSai', "Rek'Sai", '렉사이' ],
    '427': [ 'Ivern', 'Ivern', '아이번' ],
    '429': [ 'Kalista', 'Kalista', '칼리스타' ],
    '432': [ 'Bard', 'Bard', '바드' ],
    '497': [ 'Rakan', 'Rakan', '라칸' ],
    '498': [ 'Xayah', 'Xayah', '자야' ],
    '516': [ 'Ornn', 'Ornn', '오른' ],
    '517': [ 'Sylas', 'Sylas', '사일러스' ],
    '518': [ 'Neeko', 'Neeko', '니코' ],
    '523': [ 'Aphelios', 'Aphelios', '아펠리오스' ],
    '526': [ 'Rell', 'Rell', '렐' ],
    '555': [ 'Pyke', 'Pyke', '파이크' ],
    '711': [ 'Vex', 'Vex', '벡스' ],
    '777': [ 'Yone', 'Yone', '요네' ],
    '875': [ 'Sett', 'Sett', '세트' ],
    '876': [ 'Lillia', 'Lillia', '릴리아' ],
    '887': [ 'Gwen', 'Gwen', '그웬' ]
};

export const championId_by_championName = {
    'Annie':  1,
    'Olaf':  2,
    'Galio':  3,
    'TwistedFate':  4,
    'XinZhao':  5,
    'Urgot':  6,
    'Leblanc':  7,
    'Vladimir':  8,
    'FiddleSticks':  9,
    'Kayle':  10,
    'MasterYi':  11,
    'Alistar':  12,
    'Ryze':  13,
    'Sion':  14,
    'Sivir':  15,
    'Soraka':  16,
    'Teemo':  17,
    'Tristana':  18,
    'Warwick':  19,
    'Nunu':  20,
    'MissFortune':  21,
    'Ashe':  22,
    'Tryndamere':  23,
    'Jax':  24,
    'Morgana':  25,
    'Zilean':  26,
    'Singed':  27,
    'Evelynn':  28,
    'Twitch':  29,
    'Karthus':  30,
    'Chogath':  31,
    'Amumu':  32,
    'Rammus':  33,
    'Anivia':  34,
    'Shaco':  35,
    'DrMundo':  36,
    'Sona':  37,
    'Kassadin':  38,
    'Irelia':  39,
    'Janna':  40,
    'Gangplank':  41,
    'Corki':  42,
    'Karma':  43,
    'Taric':  44,
    'Veigar':  45,
    'Trundle':  48,
    'Swain':  50,
    'Caitlyn':  51,
    'Blitzcrank':  53,
    'Malphite':  54,
    'Katarina':  55,
    'Nocturne':  56,
    'Maokai':  57,
    'Renekton':  58,
    'JarvanIV':  59,
    'Elise':  60,
    'Orianna':  61,
    'MonkeyKing':  62,
    'Brand':  63,
    'LeeSin':  64,
    'Vayne':  67,
    'Rumble':  68,
    'Cassiopeia':  69,
    'Skarner':  72,
    'Heimerdinger':  74,
    'Nasus':  75,
    'Nidalee':  76,
    'Udyr':  77,
    'Poppy':  78,
    'Gragas':  79,
    'Pantheon':  80,
    'Ezreal':  81,
    'Mordekaiser':  82,
    'Yorick':  83,
    'Akali':  84,
    'Kennen':  85,
    'Garen':  86,
    'Leona':  89,
    'Malzahar':  90,
    'Talon':  91,
    'Riven':  92,
    'KogMaw':  96,
    'Shen':  98,
    'Lux':  99,
    'Xerath':  101,
    'Shyvana':  102,
    'Ahri':  103,
    'Graves':  104,
    'Fizz':  105,
    'Volibear':  106,
    'Rengar':  107,
    'Varus':  110,
    'Nautilus':  111,
    'Viktor':  112,
    'Sejuani':  113,
    'Fiora':  114,
    'Ziggs':  115,
    'Lulu':  117,
    'Draven':  119,
    'Hecarim':  120,
    'Khazix':  121,
    'Darius':  122,
    'Jayce':  126,
    'Lissandra':  127,
    'Diana':  131,
    'Quinn':  133,
    'Syndra':  134,
    'AurelionSol':  136,
    'Kayn':  141,
    'Zoe':  142,
    'Zyra':  143,
    'Kaisa':  145,
    'Seraphine':  147,
    'Gnar':  150,
    'Zac':  154,
    'Yasuo':  157,
    'Velkoz':  161,
    'Taliyah':  163,
    'Camille':  164,
    'Akshan':  166,
    'Braum':  201,
    'Jhin':  202,
    'Kindred':  203,
    'Jinx':  222,
    'TahmKench':  223,
    'Viego':  234,
    'Senna':  235,
    'Lucian':  236,
    'Zed':  238,
    'Kled':  240,
    'Ekko':  245,
    'Qiyana':  246,
    'Vi':  254,
    'Aatrox':  266,
    'Nami':  267,
    'Azir':  268,
    'Yuumi':  350,
    'Samira':  360,
    'Thresh':  412,
    'Illaoi':  420,
    'RekSai':  421,
    'Ivern':  427,
    'Kalista':  429,
    'Bard':  432,
    'Rakan':  497,
    'Xayah':  498,
    'Ornn':  516,
    'Sylas':  517,
    'Neeko':  518,
    'Aphelios':  523,
    'Rell':  526,
    'Pyke':  555,
    'Vex':  711,
    'Yone':  777,
    'Sett':  875,
    'Lillia':  876,
    'Gwen':  887
};